### ISSUE TITLE
Issue while pip installing fft package

### ISSUE THREAD

**Issue by fswerty** [locuslab/pytorch_fft#14]
I have following issue while installing pytorch-fft package

![capture](https://user-images.githubusercontent.com/8209577/32701479-806d3592-c7f8-11e7-8a17-ec8b1b5bf217.PNG)

**Comment by riceric22** [comment]
This looks like an issue with the ffi_extension package handling Windows style path names, are you able to run the examples [here](https://github.com/pytorch/extension-ffi)?

**Comment by zaczou** [comment]
@fswerty @riceric22  i got the same issue when i pip install pytorch-fft on windows.

**Comment by bloodmage** [comment]
I made a ugly hack and successfully installed this plugin.

https://github.com/bloodmage/pytorch_fft

I also added an compiled egg, you may try your luck.

**Comment by kyillene** [comment]
I tried the "hacked one" on windows 10 got the following errors;

```
(C:\ProgramData\Anaconda3\envs\pytorchenv) C:\Users\MONSTER\Desktop\pytorch_fft-master>python setup.py build
Including CUDA code.
Including CUDA code.
running build
running build_py
creating build\lib.win-amd64-3.6\pytorch_fft\_ext\fft
copying pytorch_fft\_ext\fft\autograd.py -> build\lib.win-amd64-3.6\pytorch_fft\_ext\fft
copying pytorch_fft\_ext\fft\fft.py -> build\lib.win-amd64-3.6\pytorch_fft\_ext\fft
copying pytorch_fft\_ext\fft\__init__.py -> build\lib.win-amd64-3.6\pytorch_fft\_ext\fft
copying pytorch_fft\_ext\th_fft\__init__.py -> build\lib.win-amd64-3.6\pytorch_fft\_ext\th_fft
running build_ext
generating cffi module 'build\\temp.win-amd64-3.6\\Release\\_th_fft.c'
already up-to-date
building '_th_fft' extension
cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWITH_CUDA -IC:\ProgramData\Anaconda3\envs\pytorchenv\lib\site-packages\torch\utils\ffi\..\..\lib\include -IC:\ProgramData\Anaconda3\envs\pytorchenv\lib\sit
e-packages\torch\utils\ffi\..\..\lib\include\TH -IC:\ProgramData\Anaconda3\envs\pytorchenv\lib\site-packages\torch\utils\ffi\..\..\lib\include\THC -IC:\Users\MONSTER\Desktop\pytorch_fft-master/pytorch
_fft/src "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\include" -IC:\ProgramData\Anaconda3\envs\pytorchenv\include -IC:\ProgramData\Anaconda3\envs\pytorchenv\include "-IC:\Program Files (
x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Progr
am Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um" "-IC:\P
rogram Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt" /Tcbuild\temp.win-amd64-3.6\Release\_th_fft.c /Fobuild\temp.win-amd64-3.6\Release\build\temp.win-amd64-3.6\Release\_th_fft.obj
error: command 'cl.exe' failed with exit status -1073741515

```

**Comment by bloodmage** [comment]
What's your cl.exe version? Does it match the version of your toolset?
I analysed build flags, there are few differences:

Yours:
cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWITH_CUDA 
-IC:\ProgramData\Anaconda3\envs\pytorchenv\lib\site-packages\torch\utils\ffi\..\..\lib\include 
-IC:\ProgramData\Anaconda3\envs\pytorchenv\lib\site-packages\torch\utils\ffi\..\..\lib\include\TH 
-IC:\ProgramData\Anaconda3\envs\pytorchenv\lib\site-packages\torch\utils\ffi\..\..\lib\include\THC 
-IC:\Users\MONSTER\Desktop\pytorch_fft-master/pytorch_fft/src 
"-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\include" 
-IC:\ProgramData\Anaconda3\envs\pytorchenv\include 
-IC:\ProgramData\Anaconda3\envs\pytorchenv\include 
"-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" 
"-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" 
"-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" 
"-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" 
"-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared" 
"-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um" 
"-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt" 
/Tcbuild\temp.win-amd64-3.6\Release\_th_fft.c 
/Fobuild\temp.win-amd64-3.6\Release\build\temp.win-amd64-3.6\Release\_th_fft.obj

Mine:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DWITH_CUDA 
-IC:\Anaconda\envs\py3\lib\site-packages\torch\utils\ffi\..\..\lib\include 
-IC:\Anaconda\envs\py3\lib\site-packages\torch\utils\ffi\..\..\lib\include\TH 
-IC:\Anaconda\envs\py3\lib\site-packages\torch\utils\ffi\..\..\lib\include\THC 
"-IC:\Program Files\NVIDIA Corporation\NvToolsExt\/include" 
-IC:\Users\Administrator\Documents\GitHub\pytorch_fft/pytorch_fft/src 
"-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\include" 
-IC:\Anaconda\envs\py3\include 
-IC:\Anaconda\envs\py3\include 
"-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" 
"-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" 
"-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" 
"-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" 
"-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" 
"-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" 
"-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" 
/Tcbuild\temp.win-amd64-3.6\Release\_th_fft.c 
/Fobuild\temp.win-amd64-3.6\Release\build\temp.win-amd64-3.6\Release\_th_fft.obj

**Comment by bloodmage** [comment]
1073741515 means some dll cannot be found.
Maybe you should install some extra windows toolset.

https://stackoverflow.com/questions/22038660/visual-studio-2013-cl-exe-exited-with-code-1073741515

**Comment by iariav** [comment]
Hi,
i 'm also working on windows (10), i followd the steps bloodmage suggested but when i try to run `python -c "import pytorch_fft"` i get:
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\iariav\Anaconda3\envs\pytorch\lib\site-packages\pytorch_fft\__init__.py", line 1, in <module>
    from . import fft
  File "C:\Users\iariav\Anaconda3\envs\pytorch\lib\site-packages\pytorch_fft\fft\__init__.py", line 1, in <module>
    from .fft import *
  File "C:\Users\iariav\Anaconda3\envs\pytorch\lib\site-packages\pytorch_fft\fft\fft.py", line 3, in <module>
    from .._ext import th_fft
  File "C:\Users\iariav\Anaconda3\envs\pytorch\lib\site-packages\pytorch_fft\_ext\th_fft\__init__.py", line 3, in <module>
    from ._th_fft import lib as _lib, ffi as _ffi
ImportError: DLL load failed: The specified module could not be found.`

any idea what it could be?
i made sure all compiled files are where they should (i have the _th_fft.pyd file at the th_fft folder)

thanks

**Comment by bloodmage** [comment]
Pytorch is updated, the thc.dll is combined into aten.dll, thus aten.lib needs to be regenerated and dependency of thc.dll/lib needs to be removed. Check my most recent version or regenerate aten.lib by yourself and remove 'thc' from build.py. That should work.
