### ISSUE TITLE
Build issue: No module named _th_fft

### ISSUE THREAD

**Issue by vadimkantorov** [locuslab/pytorch_fft#26]
I've installed pytorch_fft from source using `python setup.py install --prefix=/my/prefix`. I'm getting an error:
```python
import pytorch_fft
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File "pytorch_fft/__init__.py", line 1, in <module>
#    from . import fft
#  File "pytorch_fft/fft/__init__.py", line 1, in <module>
#    from .fft import *
#  File "pytorch_fft/fft/fft.py", line 3, in <module>
#    from .._ext import th_fft
#  File "pytorch_fft/_ext/th_fft/__init__.py", line 3, in <module>
#    from ._th_fft import lib as _lib, ffi as _ffi
#ImportError: No module named _th_fft
```

It seems the installer is confused (note the strange `/home/...` directory structure):
```shell
pytorch_fft $ find build/
#build/
#build/lib.linux-x86_64-2.7
#build/lib.linux-x86_64-2.7/_th_fft.so
#build/lib.linux-x86_64-2.7/pytorch_fft
#build/lib.linux-x86_64-2.7/pytorch_fft/fft
#build/lib.linux-x86_64-2.7/pytorch_fft/fft/autograd.py
#build/lib.linux-x86_64-2.7/pytorch_fft/fft/__init__.py
#build/lib.linux-x86_64-2.7/pytorch_fft/fft/fft.py
#build/lib.linux-x86_64-2.7/pytorch_fft/__init__.py
#build/lib.linux-x86_64-2.7/pytorch_fft/_ext
#build/lib.linux-x86_64-2.7/pytorch_fft/_ext/__init__.py
#build/lib.linux-x86_64-2.7/pytorch_fft/_ext/th_fft
#build/lib.linux-x86_64-2.7/pytorch_fft/_ext/th_fft/__init__.py
#build/temp.linux-x86_64-2.7
#build/temp.linux-x86_64-2.7/_th_fft.c
#build/temp.linux-x86_64-2.7/build
#build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7
#build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_th_fft.o
#build/temp.linux-x86_64-2.7/home
#build/temp.linux-x86_64-2.7/home/mscho
#build/temp.linux-x86_64-2.7/home/mscho/vadim
#build/temp.linux-x86_64-2.7/home/mscho/vadim/pytorch_fft
#build/temp.linux-x86_64-2.7/home/mscho/vadim/pytorch_fft/pytorch_fft
#build/temp.linux-x86_64-2.7/home/mscho/vadim/pytorch_fft/pytorch_fft/src
#build/temp.linux-x86_64-2.7/home/mscho/vadim/pytorch_fft/pytorch_fft/src/th_fft_cuda.o
#build/bdist.linux-x86_64
```

**Comment by vadimkantorov** [comment]
Building locally by `python setup.py build` doesn't work. Building locally by `python build.py` works fine.

**Comment by riceric22** [comment]
I wonder if this is an issue with how the extensions-ffi package handles file extensions. Can you check if you get proper behavior using --prefix on one of their examples https://github.com/pytorch/extension-ffi ?

**Comment by gdlg** [comment]
Hi @riceric22 
I can reproduce the problem. It seems that the problem was introduced by the last commit 390b2c0a126dc5b942cccca8c8634b6ec213c72c.
However to reproduce the problem, you need a clean version of the code with no leftover build files from a previously successful build. If you have successfully built the project with an older version, you won’t notice the problem.

To trigger the problem, either clone the repository fresh from Github or remove the build folders:
`rm build/ dist/ pytorch_fft.egg-info/ -Rf`
then run `python setup.py install`.

I think that 390b2c0a126dc5b942cccca8c8634b6ec213c72c is not the correct fix for #23 however it breaks the install for quite a few persons and it would be better to revert it.

**Comment by riceric22** [comment]
Thanks @gdlg for your help in reproducing the issue! My understanding now is that installs using `python setup.py` needs `package=True`, whereas building it manually with `python build.py` requires `package=False` (so `package=False` still fixes #23). However I agree that more people will probably be using setup.py instead, so I've reverted the commit as per your suggestion.

**Comment by riceric22** [comment]
I hadn't even realized it didn't have the latest version! The latest version with Rfft and its variants is now on Pypi under version 0.15

**Comment by gdlg** [comment]
Thanks.
