### ISSUE TITLE
Cuda 9.1

### ISSUE THREAD

**Issue by BradMcDanel** [locuslab/pytorch_fft#27]
After install with
`pip install pytorch_fft`

 and running
`python -c "import pytorch_fft"`

I get the following traceback:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/env/lib/python3.5/site-packages/pytorch_fft/__init__.py", line 1, in <module>  from . import fft
  File "/env/lib/python3.5/site-packages/pytorch_fft/fft/__init__.py", line 1, in <module>  from .fft import *
  File "/env/lib/python3.5/site-packages/pytorch_fft/fft/fft.py", line 3, in <module>  from .._ext import th_fft
  File "/env/lib/python3.5/site-packages/pytorch_fft/_ext/th_fft/__init__.py", line 3, in <module>  from ._th_fft import lib as _lib, ffi as _ffi
ImportError: libcufft.so.9.1: cannot open shared object file: No such file or directory

I am using python 3.5 with CUDA 9.1. Perhaps this does not work with CUDA 9.1? 

When I run:
`ls $LD_LIBRARY_PATH | grep libcufft.so.9.1`
I get:
libcufft.so.9.1
libcufft.so.9.1.85

So it does appear that the shared libraries should be found by python. Any idea? Thanks.

**Comment by riceric22** [comment]
A quick search suggests that the only issue should be with `$LD_LIBRARY_PATH`, perhaps your python environment has a different value set for that? Try checking `os.environ['LD_LIBRARY_PATH']` within your python interpreter.
