### ISSUE TITLE
CUFFT error: Plan creation failed

### ISSUE THREAD

**Issue by idansc** [locuslab/pytorch_fft#29]
I have some issues installing this package. I tried pip install, but it installed old version with Rfft missing. 
When I tried to install manually, 
I ran:
>>python build.py
>>python setup.py install

Then running test.py I got the following error: 

```
>> python test.py
CUFFT error: Plan creation failedTraceback (most recent call last):
  File "test.py", line 149, in <module>
    test_c2c(*args)
  File "test.py", line 29, in test_c2c
    run_c2c(x, z, _f1, _f2, _if1, _if2, 1e-6)
  File "test.py", line 13, in run_c2c
    assert np.allclose(y1.cpu().numpy(), y_np.real, atol=atol)
AssertionError

```

Any idea what's wrong? 
Thanks

**Comment by idansc** [comment]
Upgrading CUDA from 7.5 to 9,1 solved that matter.
