### ISSUE TITLE
Install not working with pip

### ISSUE THREAD

**Issue by zaccharieramzi** [locuslab/pytorch_fft#40]
When I do `pip install pytorch-fft`, I get the following error:

```
Collecting pytorch-fft
  Downloading https://files.pythonhosted.org/packages/9d/63/9d4a93f1c197f2a0d4f0a5ea7406da0d2bdc084be5826087c235da23eb4b/pytorch_fft-0.15.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-k3e2_fwg/pytorch-fft/setup.py", line 6, in <module>
        import build
      File "/tmp/pip-install-k3e2_fwg/pytorch-fft/build.py", line 3, in <module>
        from torch.utils.ffi import create_extension
      File "/volatile/home/Zaccharie/workspace/[project]/venv/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
        raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
    ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-k3e2_fwg/pytorch-fft/
```

**Comment by zaccharieramzi** [comment]
Apparently this is linked to the `pytorch` version, unfortunate.

**Comment by zaccharieramzi** [comment]
Oh I just saw: 
> Update: FFT functionality is now officially in PyTorch 0.4, see the documentation here. This repository is only useful for older versions of PyTorch, and will no longer be updated.

Sorry about that, closing.
